### ISSUE TITLE
Include resources_per_worker when configuring RayPlugin / RayShardedPlugin 

### ISSUE THREAD

**Issue by pablete** [ray-project/ray_lightning#100]
I have a large cluster deployed in AWS that has a mix of workers with:
`acceleator_type:T4` ,  `accelerator_type:V100`, and `accelerator_tyep:A100`

Currently there is no way one can specify `resources_per_worker` in `RayPlugin` to schedule into a different group of workers.
Like:
```
RayPlugin(...
resources_per_worker={"GPU": 1, "CPU": 4, "accelerator_type:T4": 0.01}
)
```
This flexibility is already implemented in Ray Train https://github.com/ray-project/ray/blob/master/python/ray/train/trainer.py#L90

Thanks

**Comment by igorgad** [comment]
Hi @pablete, I did some improvements in this regard on a fork I currently hold on my personal account. Happy to submit a PR if the authors here think it's worth it.

https://github.com/igorgad/ray_lightning/blob/main/ray_lightning/ray_ddp.py

**Comment by richardliaw** [comment]
@igorgad a PR would be greatly appreciated :)
