### ISSUE TITLE
RayEnvironment.creates_children should now be RayEnvironment.creates_processes_externally.

### ISSUE THREAD

**Issue by zdenek-syntensor** [ray-project/ray_lightning#101]
As per the recent removal of the deprecated creates_children in pytorch-lighting [commit](https://github.com/PyTorchLightning/pytorch-lightning/pull/10339).

Otherwise throws with `Can't instantiate abstract class RayEnvironment with abstract methods creates_processes_externally`.

**Comment by richardliaw** [comment]
Is anyone interested in making a PR to migrate this forward?

**Comment by grechaw** [comment]
@richardliaw I made a PR for this -- I'm not sure what kind of test I could quickly run to make sure it works.

**Comment by amogkam** [comment]
We have support for PTL 1.5 now that https://github.com/ray-project/ray_lightning/pull/115 is merged!
