### ISSUE TITLE
How to set find_unused_parameters?

### ISSUE THREAD

**Issue by athenawisdoms** [ray-project/ray_lightning#27]
We started noticing the below warning recently, how can be set `find_unused_parameters=False`?

> Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters. This flag results in an extra traversal of the autograd graph every iteration, which can adversely affect performance. If your model indeed never has any unused parameters, consider turning this flag off. Note that this warning may be a false positive your model has flow control causing later iterations to have unused parameters. (function operator())

With vanilla Lightning, there is an option in `DDPPlugin` to toggle this setting

```
DDPPlugin(find_unused_parameters=False)
```

Thank you!

**Comment by amogkam** [comment]
Ah yes that's a good point. After #28 gets merged you should be able to pass in `find_unused_parameters` kwarg to `RayPlugin`, along with any additional args to pass into `DistributedDataParallel`
