### ISSUE TITLE
Wandb pytorch lightning integration bug

### ISSUE THREAD

**Issue by griff4692** [ray-project/ray_lightning#31]
I am trying to tune hyper-params across 2 GPUs so I installed ray_lightning.  Yet, I am running into the following error with wandb.

`wandb: Network error (ReadTimeout), entering retry loop. See wandb/debug-internal.log for full traceback.`

Any ideas?  Thanks

**Comment by amogkam** [comment]
@griff4692 do you have a longer stack trace? And also do you mind sharing your code? Is the wandb error coming from the Tune side or the Pytorch Lightning side?

**Comment by griff4692** [comment]
Hi!

Thanks - I actually solved it by just removing wandb for distributed training.  Yet I am now confused with how to set 

```
resources_per_trial={
  'cpu': 4,
  'gpu': 2
}
```

I have 2 RTX 3090s and 64 CPUs.  

I am passing

```
pl.Trainer(...gpus=2)
```

However I am getting the following error from pytorch_lightning

```  File "/home/griffin/cl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 319, in __init__
    self.accelerator_connector = AcceleratorConnector(
  File "/home/griffin/cl/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 119, in __init__
    self.parallel_device_ids = device_parser.parse_gpu_ids(self.gpus)
  File "/home/griffin/cl/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 81, in parse_gpu_ids
    gpus = _sanitize_gpu_ids(gpus)
  File "/home/griffin/cl/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 142, in _sanitize_gpu_ids
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0, 1]
 But your machine only has: [0]
```

Oddly enough, this only happens when I use the raylightning plugin.  Not sure what's going on

**Comment by griff4692** [comment]
To follow up [0, 1] are both visible

**Comment by amogkam** [comment]
Great, glad you were able to resolve the wandb issue @griff4692! I am going to close this issue, but I created a new one for your GPU error.
