### ISSUE TITLE
Ray cluster with CPU head + GPUs Workers - No GPUs available

### ISSUE THREAD

**Issue by igorgad** [ray-project/ray_lightning#64]
Hi, I'm trying to use the RayShardedPlugin plugin on a CPU head + GPU workers Ray cluster. However, PL currently complains about not having any GPUs available. Is there any workaround for this use case?

```
pytorch_lightning.utilities.exceptions.MisconfigurationException: Error instantiating 'pytorch_lightning.trainer.trainer.Trainer' : You requested GPUs: [0]
 But your machine only has: []
```
Thanks,.

**Comment by amogkam** [comment]
@igorgad can you set `gpus=0` in your `Trainer`, but still set `use_gpu` in the `RayPlugin`

**Comment by igorgad** [comment]
Thanks @amogkam, it worked great. The documentation needs some update though.
