### ISSUE TITLE
GPU memory is higher than expected

### ISSUE THREAD

**Issue by igorgad** [ray-project/ray_lightning#73]
Hi, thanks for this project.
I've been following the recent updates and strangely the models/checkpoints that used to fit on gpu memory do not fit anymore. I think it was introduced [here](4dcbdf0aa4a94c48c53c4263c380ead3dca6fea7), and it seems that the model/checkpoint is loaded twice in the gpu rank 0.

Thanks,.

**Comment by amogkam** [comment]
Hey @igorgad thanks for posting the issue! The link seems to be broken for me. Which code change are you referring to?

**Comment by igorgad** [comment]
Hi, sorry about that. I think it was introduced in this commit: 
https://github.com/ray-project/ray_lightning/commit/4dcbdf0aa4a94c48c53c4263c380ead3dca6fea7

**Comment by amogkam** [comment]
Got it, do you have a small script that I can run showcasing this behavior? Also what did you use to identify that the model is being loaded twice?

**Comment by amogkam** [comment]
Hey @igorgad I tried this out on a simple example and I'm not seeing any additional GPU memory usage with this commit vs. without.

I'm happy to help debug this if you can provide a reproducible script.

**Comment by igorgad** [comment]
Hi @amogkam, there's no need.
I just found a bug in my 'init_hook` that went unnoticed. I'm terribly sorry about creating this issue and I'll close it for now.
But if I may, here are a couple of things that you might want to change:
- Documentation and examples use `cpus_per_worker` while the code has `num_cpus_per_worker`
- In my fork, I added options to customize resources and accelerator_type, as it would make it easier to control placement on a multi-configuration cluster.

Regarding placement, what's the best way to enforce strick_pack placement? I tried to use placement_groups from the remote options but was unsuccessful.
Thanks,.

**Comment by amogkam** [comment]
Hey @igorgad no worries! For the documentation, that's a good catch! These things are easy to miss so I really appreciate the feedback here.

Regarding placement, do you mind posting this as another issue/feature request with some more details? In particular, I'm curious about your use case- why do you need these advanced placement options and strict pack? Thanks!

**Comment by igorgad** [comment]
@amogkam hi, it turns out I'm able to control placement with the `resources` option. Thank you for your interest in this.
