### ISSUE TITLE
Ray lightning not using GPU

### ISSUE THREAD

**Issue by import-antigravity** [ray-project/ray_lightning#77]
I'm trying to use the new version of ray_lightning but I get the following warning from Tune:

```
2021-08-17 12:26:32,703	WARNING tune.py:495 -- Tune detects GPUs, but no trials are using GPUs. To enable trials to use GPUs, set tune.run(resources_per_trial={'gpu': 1}...) which allows Tune to expose 1 GPU to each trial. You can also override `Trainable.default_resource_request` if using the Trainable API.
```

I printed out the PlacementGroupFactory resources requested by `get_tune_ddp_resources` and it is requesting GPUs:
```
INFO:root:resources [{'CPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}, {'CPU': 1.0, 'GPU': 1.0}]
```

Checking the Ray dashboard confirms that GPUs are not actually being used for training.

**Comment by import-antigravity** [comment]
Additional info: I'm running on a SLURM cluster with the following conda dependencies:

```
channels:
  - pytorch
  - nvidia
  - conda-forge
  - fastai
  - defaults
dependencies:
  - conda-build
  - cudatoolkit==11.0|10.1|9.0
  - fastprogress
  - jupyter
  - matplotlib
  - pip
  - python==3.8
  - pytorch==1.8.1
  - pytorch-lightning==1.4.1
  - seaborn
  - scikit-learn
  - toml
  - tensorboard
  - torchmetrics
  - torchvision
  - pip:
      - lmdb
      - pytorch-fid
      - 'ray[default]'
      - 'ray[tune]'
      - 'ray[rllib]'
      - ray_lightning==0.1.0
```

**Comment by amogkam** [comment]
Hey @import-antigravity thanks for raising this issue!

Could you also share your code, or a reproducible script showing the bug?

**Comment by import-antigravity** [comment]
https://colab.research.google.com/drive/1MQuL8gV62ZZYksoJDMSuZE4rpLWR1Fe8?usp=sharing

This shows the warning as well as pytorch lightning showing GPUs not available

**Comment by import-antigravity** [comment]
It looks like my CUDA actually wasn't set up correctly, oops! I'm now having an unrelated issue that I messaged you on Slack about
