### ISSUE TITLE
Not possible to limit number of checkpoints written

### ISSUE THREAD

**Issue by import-antigravity** [ray-project/ray_lightning#92]
Currently `ray_lightning.tune.TuneReportCheckpointCallback` simply writes new checkpoints every time it's called, which can really add up if you're doing it every epoch (such as with PBT, etc.) It would be nice if it were able to somehow delete checkpoints after not being needed anymore.

**Comment by amogkam** [comment]
Hey @import-antigravity, you can do this by setting the `keep_checkpoints_num` argument in `tune.run`. https://docs.ray.io/en/latest/tune/api_docs/execution.html#ray.tune.run

**Comment by import-antigravity** [comment]
Awesome, thanks! I didn't realize it was compatible with that flag.
