### ISSUE TITLE
Bad argument name in RayPlugin

### ISSUE THREAD

**Issue by Nesqulck** [ray-project/ray_lightning#95]
Hey just a minor issue if at all. I noticed that in RayPlugin there exists an argument "num_cpus_per_worker" but in get_tune_ddp_resources it is called "cpus_per_worker". I can imagine that this might lead to some confusion since the num_workers and use_gpus are the same in both. I don't know if this is intentional.

**Comment by amogkam** [comment]
Thanks for catching this! No this was not intentional. I'll rename the args to standardize on `num_cpus_per_worker`.
